### PR TITLE
enable permalinks

### PR DESCRIPTION
**Pull request by tilmanb**
This extracts a method to add elements to the plot, which in turn enables us to manage permalinks by calling that function with parameters from the URL hash. Also includes a permalink html element which will set the document hash to a value that can then be shared. Fixes issue GIScience/oshdb#6

### CODE REVIEW

**Comment by tyrasd** [comment]
slightly related: https://github.com/GIScience/ohsome-dashboard/issues/2 :wink:

**Comment by tyrasd** [comment]
Cool, thanks a lot!
I hope you don't mind that I've changed a few things here and there (see the additional [commits](https://github.com/tyrasd/taghistory/pull/27/commits) and their messages). What do you think?

**Comment by tilmanb** [comment]
Thanks for your edits! I'm totally good with them.

**Comment by tyrasd** [comment]
it's live now. example: https://taghistory.raifer.tech/#***/amenity/bench&***/natural/tree&node/building/
please let me know if there are any issues :)

**Pull request merged**
